name: jardinemirativ2
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  badges: ^2.0.3
  cloud_firestore: ^3.1.15
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.6.0
  enum_to_string: ^2.0.1
  firebase: ^9.0.3
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  flutter:
    sdk: flutter
  http: ^0.13.4
  image_picker: ^0.8.5+3
  outline_gradient_button: ^2.0.0+1
  pdf: ^3.8.1
  pluto_grid: ^3.1.1
  url_strategy: ^0.2.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic
        - asset: assets/fonts/HelveticaNeueBold.ttf
          weight: 700
